# generated by datamodel-codegen:
#   filename:  remove_moderator.json

from __future__ import annotations

from pydantic import BaseModel


class RemoveModeratorParameter(BaseModel):
    __root__: str
