# generated by datamodel-codegen:
#   filename:  update_metadata.json

from __future__ import annotations

from typing import Dict, Optional, Union

from pydantic import BaseModel


class UpdateMetadataParameter(BaseModel):
    __root__: Optional[Union[int, Dict[str, str]]] = {}
