# generated by datamodel-codegen:
#   filename:  seed_token.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SeedTokenParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    author: str
    balance: str
    enabled: bool
    id: str
    metadata: str
    price: str
    royalties: str
    supply: str
    timestamp: str
