# generated by datamodel-codegen:
#   filename:  update_issuer.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateIssuerParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    enabled: bool
    issuer_id: str
    price: str
    royalties: str
