# generated by datamodel-codegen:
#   filename:  set_objkt_contract.json

from __future__ import annotations

from pydantic import BaseModel


class SetObjktContractParameter(BaseModel):
    __root__: str
