# generated by datamodel-codegen:
#   filename:  set_administrator.json

from __future__ import annotations

from pydantic import BaseModel


class SetAdministratorParameter(BaseModel):
    __root__: str
