# generated by datamodel-codegen:
#   filename:  set_metadata.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class SetMetadataParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    k: str
    v: str
