# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Offers(BaseModel):
    class Config:
        extra = Extra.forbid

    creator: str
    issuer: str
    objkt_amount: str
    objkt_id: str
    price: str
    royalties: str


class OfferStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    counter: str
    enabled: bool
    fees: str
    metadata: Dict[str, str]
    objkts: str
    offers: Dict[str, Offers]
    treasury: str
